_format_version: "3.0"
services:
- host: httpbin.org
  name: NAMyServiceAPIApigee
  path: /
  port: 443
  protocol: https
  routes:
  - methods:
    - GET
    name: NAMyServiceAPIApigee-getIpAddress
    paths:
    - ~/ip$
    strip_path: false
    tags:
    - OAS3_import
    - OAS3file_testing.yaml
  tags:
  - OAS3_import
  - OAS3file_testing.yaml
