_format_version: "3.0"
services:
- host: mocktarget.apigee.net
  name: Margin
  path: /Sandbox/v1.1/json
  plugins:
  - name: basic-auth
    tags:
    - OAS3_import
    - OAS3file_spec.yaml
  port: 443
  protocol: https
  routes:
  - methods:
    - POST
    name: Margin-LCRMReport
    paths:
    - ~/MarginsCalculator/LCRMReport$
    strip_path: false
    tags:
    - OAS3_import
    - OAS3file_spec.yaml
  - methods:
    - GET
    name: Margin-LCRMReportFile
    paths:
    - ~/MarginsCalculator/LCRMReportFile$
    strip_path: false
    tags:
    - OAS3_import
    - OAS3file_spec.yaml
  tags:
  - OAS3_import
  - OAS3file_spec.yaml
