_format_version: "1.1"
services:
  - name: NAMyServiceAPIApigee
    protocol: https
    host: httpbin.org
    port: 443
    path: /
    plugins: []
    routes:
      - tags:
          &a1
          - OAS3_import
          - OAS3file_testing.yaml
        name: NAMyServiceAPIApigee-getIpAddress
        methods:
          - GET
        paths:
          - /ip$
        strip_path: false
    tags: *a1
