_format_version: "1.1"
services:
  - name: Margin
    protocol: https
    host: mocktarget.apigee.net
    port: 443
    path: /Sandbox/v1.1/json
    plugins:
      - name: basic-auth
        tags:
          - OAS3_import
          - OAS3file_spec.yaml
    routes:
      - tags:
          &a1
          - OAS3_import
          - OAS3file_spec.yaml
        name: Margin-LCRMReport
        methods:
          - POST
        paths:
          - /MarginsCalculator/LCRMReport$
        strip_path: false
      - tags: *a1
        name: Margin-LCRMReportFile
        methods:
          - GET
        paths:
          - /MarginsCalculator/LCRMReportFile$
        strip_path: false
    tags: *a1
